use_frameworks!

platform :ios, '10.0'

target 'MixedNetworkSys_Example' do
  pod 'thenPromise'
  pod 'MixedNetworkSys', :path => '../'

  target 'MixedNetworkSys_Tests' do
    inherit! :search_paths

    
  end
end
